-- MVP-2 : suivi des paiements d'abonnement (trace comptable de la plateforme).
CREATE TABLE paiements (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    etablissement_id BIGINT      NOT NULL REFERENCES etablissements(id),
    montant          BIGINT      NOT NULL,
    mois_credites    INTEGER     NOT NULL DEFAULT 1,
    reference        VARCHAR(255),
    date_paiement    TIMESTAMP   NOT NULL DEFAULT now(),
    enregistre_par   VARCHAR(255)
);
CREATE INDEX idx_paiements_etablissement ON paiements(etablissement_id);
CREATE INDEX idx_paiements_date ON paiements(date_paiement);
