-- Baseline du schema SIGEP (genere depuis le schema existant)
-- Gere par Flyway. Ne pas modifier : pour evoluer, ajouter V2__*.sql, V3__*.sql, ...
--
-- PostgreSQL database dump
--


-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1




--
-- Name: classes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.classes (
    id bigint NOT NULL,
    filiere character varying(255),
    libelle character varying(255) NOT NULL,
    niveau integer
);


--
-- Name: classes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.classes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.classes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: demandes_rattrapage; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.demandes_rattrapage (
    id bigint NOT NULL,
    date_creation timestamp(6) without time zone NOT NULL,
    date_souhaitee date NOT NULL,
    heure_souhaitee time(6) without time zone NOT NULL,
    motif text,
    statut character varying(255),
    classe_id bigint NOT NULL,
    enseignant_id bigint NOT NULL,
    matiere_id bigint NOT NULL,
    seance_rattrapage_id bigint,
    CONSTRAINT demandes_rattrapage_statut_check CHECK (((statut)::text = ANY ((ARRAY['EN_ATTENTE'::character varying, 'ACCEPTE'::character varying, 'REFUSE'::character varying])::text[])))
);


--
-- Name: demandes_rattrapage_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.demandes_rattrapage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.demandes_rattrapage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: emargements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.emargements (
    id bigint NOT NULL,
    date_heure timestamp(6) without time zone NOT NULL,
    qr_token_utilise character varying(255),
    signature_base64 text,
    enseignant_id bigint NOT NULL,
    seance_id bigint NOT NULL,
    en_retard boolean NOT NULL
);


--
-- Name: emargements_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.emargements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.emargements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: enseignants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.enseignants (
    id bigint NOT NULL,
    departement character varying(255),
    grade character varying(255),
    matricule character varying(255) NOT NULL,
    nom character varying(255) NOT NULL,
    photo_url character varying(255),
    prenom character varying(255) NOT NULL,
    statut character varying(255),
    user_id bigint,
    CONSTRAINT enseignants_statut_check CHECK (((statut)::text = ANY ((ARRAY['VALIDATED'::character varying, 'PENDING'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: enseignants_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.enseignants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.enseignants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: facultes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.facultes (
    id bigint NOT NULL,
    code character varying(255) NOT NULL,
    date_creation timestamp(6) without time zone NOT NULL,
    description character varying(500),
    nom character varying(255) NOT NULL
);


--
-- Name: facultes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.facultes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.facultes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: matieres; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.matieres (
    id bigint NOT NULL,
    description character varying(255),
    libelle character varying(255) NOT NULL
);


--
-- Name: matieres_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.matieres ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.matieres_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rapports_pdf; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rapports_pdf (
    id bigint NOT NULL,
    chemin_fichier character varying(255) NOT NULL,
    date_generation timestamp(6) without time zone NOT NULL,
    nom_fichier character varying(255) NOT NULL,
    periode_debut date NOT NULL,
    periode_fin date NOT NULL,
    taille_fichier_octets bigint,
    type character varying(255),
    enseignant_id bigint NOT NULL,
    CONSTRAINT rapports_pdf_type_check CHECK (((type)::text = ANY ((ARRAY['HEBDOMADAIRE'::character varying, 'MENSUEL'::character varying, 'TRIMESTRIEL'::character varying, 'PONCTUEL'::character varying])::text[])))
);


--
-- Name: rapports_pdf_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.rapports_pdf ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rapports_pdf_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    id integer NOT NULL,
    name character varying(20) NOT NULL,
    CONSTRAINT roles_name_check CHECK (((name)::text = ANY ((ARRAY['ROLE_ADMIN'::character varying, 'ROLE_ENSEIGNANT'::character varying])::text[])))
);


--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: salles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.salles (
    id bigint NOT NULL,
    batiment character varying(255),
    capacite integer,
    libelle character varying(255) NOT NULL
);


--
-- Name: salles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.salles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.salles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: seances; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.seances (
    id bigint NOT NULL,
    date date NOT NULL,
    heure_debut time(6) without time zone NOT NULL,
    heure_fin time(6) without time zone NOT NULL,
    statut character varying(255),
    type character varying(255),
    classe_id bigint NOT NULL,
    enseignant_id bigint NOT NULL,
    matiere_id bigint NOT NULL,
    salle_id bigint NOT NULL,
    CONSTRAINT seances_statut_check CHECK (((statut)::text = ANY ((ARRAY['A_FAIRE'::character varying, 'EMARGE'::character varying, 'EN_RETARD'::character varying])::text[]))),
    CONSTRAINT seances_type_check CHECK (((type)::text = ANY ((ARRAY['NORMALE'::character varying, 'RATTRAPAGE'::character varying])::text[])))
);


--
-- Name: seances_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.seances ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.seances_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_roles (
    user_id bigint NOT NULL,
    role_id integer NOT NULL
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    enabled boolean NOT NULL,
    password character varying(255) NOT NULL
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: classes classes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.classes
    ADD CONSTRAINT classes_pkey PRIMARY KEY (id);


--
-- Name: demandes_rattrapage demandes_rattrapage_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.demandes_rattrapage
    ADD CONSTRAINT demandes_rattrapage_pkey PRIMARY KEY (id);


--
-- Name: emargements emargements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.emargements
    ADD CONSTRAINT emargements_pkey PRIMARY KEY (id);


--
-- Name: enseignants enseignants_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enseignants
    ADD CONSTRAINT enseignants_pkey PRIMARY KEY (id);


--
-- Name: facultes facultes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.facultes
    ADD CONSTRAINT facultes_pkey PRIMARY KEY (id);


--
-- Name: matieres matieres_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.matieres
    ADD CONSTRAINT matieres_pkey PRIMARY KEY (id);


--
-- Name: rapports_pdf rapports_pdf_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rapports_pdf
    ADD CONSTRAINT rapports_pdf_pkey PRIMARY KEY (id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: salles salles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.salles
    ADD CONSTRAINT salles_pkey PRIMARY KEY (id);


--
-- Name: seances seances_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seances
    ADD CONSTRAINT seances_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: demandes_rattrapage ukbkyhx61xkbrub2uyc525julvu; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.demandes_rattrapage
    ADD CONSTRAINT ukbkyhx61xkbrub2uyc525julvu UNIQUE (seance_rattrapage_id);


--
-- Name: facultes ukcrpay7bud4k60gitdjo78it1h; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.facultes
    ADD CONSTRAINT ukcrpay7bud4k60gitdjo78it1h UNIQUE (code);


--
-- Name: enseignants ukf2mtugyb88xrnvy1ktrslksxm; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enseignants
    ADD CONSTRAINT ukf2mtugyb88xrnvy1ktrslksxm UNIQUE (matricule);


--
-- Name: facultes ukmqc2mu28tq0vnnxsrl97s452h; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.facultes
    ADD CONSTRAINT ukmqc2mu28tq0vnnxsrl97s452h UNIQUE (nom);


--
-- Name: emargements uknjqrb2pjekbvi8ifhc5unyh1u; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.emargements
    ADD CONSTRAINT uknjqrb2pjekbvi8ifhc5unyh1u UNIQUE (seance_id);


--
-- Name: roles ukofx66keruapi6vyqpv6f2or37; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT ukofx66keruapi6vyqpv6f2or37 UNIQUE (name);


--
-- Name: salles ukptuke9exnl35j1l2pajbno6x5; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.salles
    ADD CONSTRAINT ukptuke9exnl35j1l2pajbno6x5 UNIQUE (libelle);


--
-- Name: enseignants ukqwda9n22x9me8fiftbc9ht2pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enseignants
    ADD CONSTRAINT ukqwda9n22x9me8fiftbc9ht2pk UNIQUE (user_id);


--
-- Name: user_roles user_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: demandes_rattrapage fk3jqdhhe3e0pwov6p7dva8n9cr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.demandes_rattrapage
    ADD CONSTRAINT fk3jqdhhe3e0pwov6p7dva8n9cr FOREIGN KEY (classe_id) REFERENCES public.classes(id);


--
-- Name: demandes_rattrapage fk5frbm9pun7t86os3r0nrh5d0x; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.demandes_rattrapage
    ADD CONSTRAINT fk5frbm9pun7t86os3r0nrh5d0x FOREIGN KEY (enseignant_id) REFERENCES public.enseignants(id);


--
-- Name: demandes_rattrapage fk9cidtes4948omanr0y47au90b; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.demandes_rattrapage
    ADD CONSTRAINT fk9cidtes4948omanr0y47au90b FOREIGN KEY (matiere_id) REFERENCES public.matieres(id);


--
-- Name: seances fkbpknclbic91w2syb8m7krkrnh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seances
    ADD CONSTRAINT fkbpknclbic91w2syb8m7krkrnh FOREIGN KEY (classe_id) REFERENCES public.classes(id);


--
-- Name: emargements fkg9jqk1t47r830ew3vml9n0ipo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.emargements
    ADD CONSTRAINT fkg9jqk1t47r830ew3vml9n0ipo FOREIGN KEY (seance_id) REFERENCES public.seances(id);


--
-- Name: emargements fkgphg6mq2li6qje9op231gnfyn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.emargements
    ADD CONSTRAINT fkgphg6mq2li6qje9op231gnfyn FOREIGN KEY (enseignant_id) REFERENCES public.enseignants(id);


--
-- Name: rapports_pdf fkgpiqny786yq0b5x1r6i8ct4wi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rapports_pdf
    ADD CONSTRAINT fkgpiqny786yq0b5x1r6i8ct4wi FOREIGN KEY (enseignant_id) REFERENCES public.enseignants(id);


--
-- Name: user_roles fkh8ciramu9cc9q3qcqiv4ue8a6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- Name: user_roles fkhfh9dx7w3ubf1co1vdev94g3f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: seances fkk8iyr0m0545vm5dk1dvaoe95g; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seances
    ADD CONSTRAINT fkk8iyr0m0545vm5dk1dvaoe95g FOREIGN KEY (matiere_id) REFERENCES public.matieres(id);


--
-- Name: enseignants fknwh26dbat4ro4wy4snp34mwee; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enseignants
    ADD CONSTRAINT fknwh26dbat4ro4wy4snp34mwee FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: seances fko4u6l79k2cvoq21hulqccglj9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seances
    ADD CONSTRAINT fko4u6l79k2cvoq21hulqccglj9 FOREIGN KEY (enseignant_id) REFERENCES public.enseignants(id);


--
-- Name: demandes_rattrapage fkpre719dm6v3bs65q36bmbtkxc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.demandes_rattrapage
    ADD CONSTRAINT fkpre719dm6v3bs65q36bmbtkxc FOREIGN KEY (seance_rattrapage_id) REFERENCES public.seances(id);


--
-- Name: seances fks053jrcaajq1bugiaca04jw35; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seances
    ADD CONSTRAINT fks053jrcaajq1bugiaca04jw35 FOREIGN KEY (salle_id) REFERENCES public.salles(id);


--
-- PostgreSQL database dump complete
--


