-- Refresh tokens : sessions longue durée, révocables, avec rotation à chaque usage.
-- SECURITE : le token brut n'est jamais stocké — seule son empreinte SHA-256 (hex, 64 car.) l'est.
CREATE TABLE public.refresh_tokens (
    id bigint NOT NULL,
    token_hash character varying(64) NOT NULL,
    user_id bigint NOT NULL,
    expiry_date timestamp(6) without time zone NOT NULL,
    revoked boolean DEFAULT false NOT NULL,
    created_at timestamp(6) without time zone NOT NULL
);

ALTER TABLE public.refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT uk_refresh_tokens_token_hash UNIQUE (token_hash);

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

CREATE INDEX idx_refresh_tokens_user ON public.refresh_tokens (user_id);
